version: '3.8'

services:
  front:
    image: people-front:latest
    ports:
      - "3000:3000"
    volumes:
      - ../people-status-front/src/:/app/src/
  app:
    image: people-server:latest
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=people_status
      - OLLAMA_HOST=ollama:11434
    depends_on:
      - mysql
      - ollama
    volumes:
      - ./src/:/app/src/

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=people_status
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./people_status.sql:/docker-entrypoint-initdb.d/people_status.sql

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    # volumes:
    #   - ollama_data:/root/.ollama
      # - ./models:/root/.ollama/models  # 挂载本地的 gguf 文件到容器内的 /root/.ollama/models
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  mysql_data:
  ollama_data: 